export const localProducts = [
  {
    id: "d1",
    slug: "d1",
    name: "Elf Bar BC5000",
    brand: "Elf Bar",
    category: "disposable",
    price: 22,
    flavor: "Blueberry Ice",
    puffs: "5000 puffs",
    volume: null,
    emoji: "💨",
    color: "cyan",
    image: null,
    is_active: true,
    sort_order: 10,
  },
  {
    id: "d2",
    slug: "d2",
    name: "Lost Mary OS5000",
    brand: "Lost Mary",
    category: "disposable",
    price: 24,
    flavor: "Strawberry Kiwi",
    puffs: "5000 puffs",
    volume: null,
    emoji: "🍓",
    color: "pink",
    image: null,
    is_active: true,
    sort_order: 20,
  },
  {
    id: "d3",
    slug: "d3",
    name: "HQD Cuvie Plus",
    brand: "HQD",
    category: "disposable",
    price: 15,
    flavor: "Mango Ice",
    puffs: "1200 puffs",
    volume: null,
    emoji: "🥭",
    color: "lime",
    image: null,
    is_active: true,
    sort_order: 30,
  },
  {
    id: "v1-pink",
    slug: "v1-pink",
    name: "Vaporesso XROS Pro 2 — Pink",
    brand: "Vaporesso",
    category: "device",
    price: 90,
    flavor: "Pink",
    puffs: null,
    volume: null,
    emoji: "⚡",
    color: "pink",
    image: null,
    is_active: true,
    sort_order: 110,
  },
  {
    id: "v1-green",
    slug: "v1-green",
    name: "Vaporesso XROS Pro 2 — Green",
    brand: "Vaporesso",
    category: "device",
    price: 90,
    flavor: "Green",
    puffs: null,
    volume: null,
    emoji: "⚡",
    color: "lime",
    image: null,
    is_active: true,
    sort_order: 111,
  },
  {
    id: "v4-silver",
    slug: "v4-silver",
    name: "Vaporesso XROS 5 Mini — Silver",
    brand: "Vaporesso",
    category: "device",
    price: 55,
    flavor: "Silver",
    puffs: null,
    volume: null,
    emoji: "⚡",
    color: "cyan",
    image: null,
    is_active: true,
    sort_order: 140,
  },
  {
    id: "v5-red",
    slug: "v5-red",
    name: "Vaporesso XROS 5 — Red",
    brand: "Vaporesso",
    category: "device",
    price: 65,
    flavor: "Red",
    puffs: null,
    volume: null,
    emoji: "⚡",
    color: "pink",
    image: null,
    is_active: true,
    sort_order: 153,
  },
  {
    id: "l1",
    slug: "l1",
    name: "Jam Monster — Blueberry",
    brand: "Jam Monster",
    category: "liquid",
    price: 18,
    flavor: "Blueberry Jam",
    puffs: null,
    volume: "30ml / 20mg",
    emoji: "🫐",
    color: "cyan",
    image: null,
    is_active: true,
    sort_order: 210,
  },
  {
    id: "l2",
    slug: "l2",
    name: "Husky Salt — Ice Cola",
    brand: "Husky",
    category: "liquid",
    price: 16,
    flavor: "Ice Cola",
    puffs: null,
    volume: "30ml / 20mg",
    emoji: "🥤",
    color: "pink",
    image: null,
    is_active: true,
    sort_order: 220,
  },
  {
    id: "c2",
    slug: "c2",
    name: "SMOK Novo Pod",
    brand: "SMOK",
    category: "consumable",
    price: 8,
    flavor: "Empty Pod",
    puffs: null,
    volume: "2ml / 1.0ohm",
    emoji: "🔧",
    color: "pink",
    image: null,
    is_active: true,
    sort_order: 310,
  },
  {
    id: "c6",
    slug: "c6",
    name: "Vaporesso XROS Corex 2.0 0.6ohm",
    brand: "Vaporesso",
    category: "consumable",
    price: 13,
    flavor: "Mesh Pod",
    puffs: null,
    volume: "2ml / 0.6ohm, 1pc",
    emoji: "🧩",
    color: "lime",
    image: null,
    is_active: true,
    sort_order: 341,
  },
];
