name = "zaider437-teenvape-vibes-2b19b85e"
compatibility_date = "2026-08-03"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"

[build]
command = "PRISMA_SKIP_POSTINSTALL=true npm run build"
cwd = "."

[vars]
EMAIL_API_URL = ""
TELEGRAM_LOGIN_BOT_TOKEN = ""
TELEGRAM_API_KEY = ""
TELEGRAM_CHAT_ID = ""
ADMIN_PASSWORD_SEED = ""
PUBLIC_IMAGE_CDN_BASE = ""
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_DLmGdw_zbkrtIE-pNvtovA_jkqoDzZP"
SUPABASE_SECRET_KEY = "sb_secret_LzJIRzi7EsB-b2bZaAtYUg_juFQG2YL"
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_LzJIRzi7EsB-b2bZaAtYUg_juFQG2YL"

[dev]
port = 8087
ip = "0.0.0.0"

[assets]
binding = "ASSETS"
directory = ".output/public"